= Asciidoctor JATS
Manuel Prinz <manuel@pinguinkiste.de>
:icons: font
// Aliases:
:project-name: Asciidoctor JATS
:project-handle: asciidoctor-jats
// URIs:
:uri-asciidoctor: https://asciidoctor.org
//:uri-gem: https://rubygems.org/gems/{project-handle}
:uri-project: https://github.com/manuelprinz/{project-handle}
:uri-project-repo: {uri-project}
:uri-project-issues: {uri-project-repo}/issues
//:uri-project-list: http://discuss.asciidoctor.org
:uri-rvm: https://rvm.io

{project-name} is extension for Asciidoctor that converts AsciiDoc documents to the Journal Article Tag Suite (JATS)
 format.
JATS is an XML format for scientific papers with a wide acceptance in life science journals and journal databases.

The converter outputs XML compatible with the https://jats.nlm.nih.gov/articleauthoring/[Article Authoring Tag Set].
Other tag sets, namely _Archiving and Interchange_ and _Journal Publishing_, are out of the scope of this project.

[caption=Status]
CAUTION: {project-name} is currently _in development_. It does little more than nothing.

toc::[]

== Goal

The goal of this project is to support authors of (especially scientific) articles in writing by leveraging
 Asciidoctor's easy to learn markup and the ability to output all kinds of formats that are relevant to their work.

Documents in JATS can support the publishing process by providing a file format that is an accepted standard by
 publishers.
By Asciidoctor's philosophy to _separate content from form_ the article can be output to any format, allowing for a
 higher re-use due to publishing the work in multiple formats.

== Contributing

Bug reports and pull requests are welcome on GitHub at {uri-project}.

[[resources,Links]]
== Resources

* https://github.com/asciidoctor/asciidoctor/issues/1792[GitHub issue]
* https://jats.nlm.nih.gov/[JATS Homepage]
* https://jats.nlm.nih.gov/articleauthoring/[Article Authoring Tag Set (aka "Orange Set")]
* https://jats.nlm.nih.gov/articleauthoring/tag-library/1.1/index.html[Article Authoring Tag Library, Version 1.1]
* https://jats4r.org/[Jats for Reuse Project]
* https://www.ncbi.nlm.nih.gov/pmc/pmcdoc/tagging-guidelines/article/style.html[PMC Tagging Guidelines]

== Authors

{project-name} was written by https://github.com/manuelprinz[Manuel Prinz].
//on behalf of the Asciidoctor Project.

== Copyright

Copyright (C) 2018 Manuel Prinz

Free use of this software is granted under the terms of the MIT License.

For the full text of the license, see the <<LICENSE.adoc#,LICENSE>> file.
//Refer to the <<NOTICE#,NOTICE>> file for information about third-party Open Source software in use.
